version: 0.2

phases:
  install:
    runtime-verions:
      nodejs: 12.9.1
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build