version: 0.2

phases:
  pre_build:
    runtime-versions:
      nodejs: 12.9.1
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build